// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/api/login.ts";
import * as $6 from "./routes/api/register.ts";
import * as $7 from "./routes/greet/[name].tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/login/index.tsx";
import * as $10 from "./routes/register/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Login.tsx";
import * as $$2 from "./islands/Register.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/api/joke.ts": $4,
    "./routes/api/login.ts": $5,
    "./routes/api/register.ts": $6,
    "./routes/greet/[name].tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/login/index.tsx": $9,
    "./routes/register/index.tsx": $10,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Login.tsx": $$1,
    "./islands/Register.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
